In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from IPython.display import display, Image

In [ ]:
amazon_data = pd.read_csv("/content/amazon.csv")

In [ ]:
amazon_data.head()

product_id                                       product_name  \
0  B07JW9H4J1  Wayona Nylon Braided USB to Lightning Fast Cha...   
1  B098NS6PVG  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...   
2  B096MSW6CT  Sounce Fast Phone Charging Cable & Data Sync U...   
3  B08HDJ86NZ  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...   
4  B08CF3B7N1  Portronics Konnect L 1.2M Fast Charging 3A 8 P...   

                                            category discounted_price  \
0  Computers&Accessories|Accessories&Peripherals|...             ₹399   
1  Computers&Accessories|Accessories&Peripherals|...             ₹199   
2  Computers&Accessories|Accessories&Peripherals|...             ₹199   
3  Computers&Accessories|Accessories&Peripherals|...             ₹329   
4  Computers&Accessories|Accessories&Peripherals|...             ₹154   

  actual_price discount_percentage rating rating_count  \
0       ₹1,099                 64%    4.2       24,269   
1         ₹349                 43%    4.0       43,994   
2       ₹1,899                 90%    3.9        7,928   
3         ₹699                 53%    4.2       94,363   
4         ₹399                 61%    4.2       16,905   

                                       about_product  \
0  High Compatibility : Compatible With iPhone 12...   
1  Compatible with all Type C enabled devices, be...   
2  【 Fast Charger& Data Sync】-With built-in safet...   
3  The boAt Deuce USB 300 2 in 1 cable is compati...   
4  [CHARGE & SYNC FUNCTION]- This cable comes wit...   

                                             user_id  \
0  AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...   
1  AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...   
2  AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...   
3  AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...   
4  AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...   

                                           user_name  \
0  Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...   
1  ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...   
2  Kunal,Himanshu,viswanath,sai niharka,saqib mal...   
3  Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...   
4  rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...   

                                           review_id  \
0  R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...   
1  RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...   
2  R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...   
3  R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...   
4  R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...   

                                        review_title  \
0  Satisfied,Charging is really fast,Value for mo...   
1  A Good Braided Cable for Your Type C Device,Go...   
2  Good speed for earlier versions,Good Product,W...   
3  Good product,Good one,Nice,Really nice product...   
4  As good as original,Decent,Good one for second...   

                                      review_content  \
0  Looks durable Charging is fine tooNo complains...   
1  I ordered this cable to connect my phone to An...   
2  Not quite durable and sturdy,https://m.media-a...   
3  Good product,long wire,Charges good,Nice,I bou...   
4  Bought this instead of original apple, does th...   

                                            img_link  \
0  https://m.media-amazon.com/images/W/WEBP_40237...   
1  https://m.media-amazon.com/images/W/WEBP_40237...   
2  https://m.media-amazon.com/images/W/WEBP_40237...   
3  https://m.media-amazon.com/images/I/41V5FtEWPk...   
4  https://m.media-amazon.com/images/W/WEBP_40237...   

                                        product_link  
0  https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...  
1  https://www.amazon.in/Ambrane-Unbreakable-Char...  
2  https://www.amazon.in/Sounce-iPhone-Charging-C...  
3  https://www.amazon.in/Deuce-300-Resistant-Tang...  
4  https://www.amazon.in/Portronics-Konnect-POR-1...

In [ ]:
amazon_data['index'] = range(len(amazon_data))
amazon_data.to_csv('/content/amazon_new.csv', index=False)

In [ ]:
amazon_data.head()

product_id                                       product_name  \
0  B07JW9H4J1  Wayona Nylon Braided USB to Lightning Fast Cha...   
1  B098NS6PVG  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...   
2  B096MSW6CT  Sounce Fast Phone Charging Cable & Data Sync U...   
3  B08HDJ86NZ  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...   
4  B08CF3B7N1  Portronics Konnect L 1.2M Fast Charging 3A 8 P...   

                                            category discounted_price  \
0  Computers&Accessories|Accessories&Peripherals|...             ₹399   
1  Computers&Accessories|Accessories&Peripherals|...             ₹199   
2  Computers&Accessories|Accessories&Peripherals|...             ₹199   
3  Computers&Accessories|Accessories&Peripherals|...             ₹329   
4  Computers&Accessories|Accessories&Peripherals|...             ₹154   

  actual_price discount_percentage rating rating_count  \
0       ₹1,099                 64%    4.2       24,269   
1         ₹349                 43%    4.0       43,994   
2       ₹1,899                 90%    3.9        7,928   
3         ₹699                 53%    4.2       94,363   
4         ₹399                 61%    4.2       16,905   

                                       about_product  \
0  High Compatibility : Compatible With iPhone 12...   
1  Compatible with all Type C enabled devices, be...   
2  【 Fast Charger& Data Sync】-With built-in safet...   
3  The boAt Deuce USB 300 2 in 1 cable is compati...   
4  [CHARGE & SYNC FUNCTION]- This cable comes wit...   

                                             user_id  \
0  AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...   
1  AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...   
2  AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...   
3  AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...   
4  AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...   

                                           user_name  \
0  Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...   
1  ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...   
2  Kunal,Himanshu,viswanath,sai niharka,saqib mal...   
3  Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...   
4  rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...   

                                           review_id  \
0  R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...   
1  RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...   
2  R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...   
3  R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...   
4  R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...   

                                        review_title  \
0  Satisfied,Charging is really fast,Value for mo...   
1  A Good Braided Cable for Your Type C Device,Go...   
2  Good speed for earlier versions,Good Product,W...   
3  Good product,Good one,Nice,Really nice product...   
4  As good as original,Decent,Good one for second...   

                                      review_content  \
0  Looks durable Charging is fine tooNo complains...   
1  I ordered this cable to connect my phone to An...   
2  Not quite durable and sturdy,https://m.media-a...   
3  Good product,long wire,Charges good,Nice,I bou...   
4  Bought this instead of original apple, does th...   

                                            img_link  \
0  https://m.media-amazon.com/images/W/WEBP_40237...   
1  https://m.media-amazon.com/images/W/WEBP_40237...   
2  https://m.media-amazon.com/images/W/WEBP_40237...   
3  https://m.media-amazon.com/images/I/41V5FtEWPk...   
4  https://m.media-amazon.com/images/W/WEBP_40237...   

                                        product_link  index  
0  https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...      0  
1  https://www.amazon.in/Ambrane-Unbreakable-Char...      1  
2  https://www.amazon.in/Sounce-iPhone-Charging-C...      2  
3  https://www.amazon.in/Deuce-300-Resistant-Tang...      3  
4  https://www.amazon.in/Portronics-Konnect-POR-1...      4

In [ ]:
amazon_data.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
index                  0
dtype: int64

In [ ]:
amazon_data.dtypes

product_id             object
product_name           object
category               object
discounted_price       object
actual_price           object
discount_percentage    object
rating                 object
rating_count           object
about_product          object
user_id                object
user_name              object
review_id              object
review_title           object
review_content         object
img_link               object
product_link           object
index                   int64
dtype: object

In [ ]:
amazon_data.rating_count.values

array(['24,269', '43,994', '7,928', ..., '468', '8,031', '6,987'],
      dtype=object)

In [ ]:
amazon_data['discounted_price'] = amazon_data['discounted_price'].str.replace('[^\d.]', '', regex=True)
amazon_data['discounted_price'] = pd.to_numeric(amazon_data['discounted_price'], errors='coerce')


In [ ]:
amazon_data['actual_price'] = amazon_data['actual_price'].str.replace('[^\d.]', '', regex=True)
amazon_data['actual_price'] = pd.to_numeric(amazon_data['actual_price'], errors='coerce')

In [ ]:
amazon_data['discount_percentage'] = amazon_data['discount_percentage'].str.replace('[^\d.]', '', regex=True)
amazon_data['discounted_percentage'] = pd.to_numeric(amazon_data['discount_percentage'], errors='coerce')

In [ ]:
amazon_data['rating'] = amazon_data['rating'].str.replace('[^\d.]', '', regex=True)
amazon_data['rating'] = pd.to_numeric(amazon_data['rating'], errors='coerce')

In [ ]:
amazon_data['rating_count'] = amazon_data['rating_count'].str.replace('[^\d.]', '', regex=True)
amazon_data['rating_count'] = pd.to_numeric(amazon_data['rating_count'], errors='coerce')

In [ ]:
amazon_data.dtypes

product_id                object
product_name              object
category                  object
discounted_price         float64
actual_price             float64
discount_percentage       object
rating                   float64
rating_count             float64
about_product             object
user_id                   object
user_name                 object
review_id                 object
review_title              object
review_content            object
img_link                  object
product_link              object
index                      int64
discounted_percentage      int64
dtype: object

In [ ]:
amazon_data = amazon_data.dropna(subset=['rating_count','rating'])

In [ ]:
amazon_data.isnull().sum()

product_id               0
product_name             0
category                 0
discounted_price         0
actual_price             0
discount_percentage      0
rating                   0
rating_count             0
about_product            0
user_id                  0
user_name                0
review_id                0
review_title             0
review_content           0
img_link                 0
product_link             0
index                    0
discounted_percentage    0
dtype: int64

In [ ]:
#selecting relevant features for recommendation

selected_features = ['product_name', 'category', 'about_product',  'img_link', 'product_link', 'review_title', 'review_content']
print(selected_features)

['product_name', 'category', 'about_product', 'img_link', 'product_link', 'review_title', 'review_content']


In [ ]:
combined_features = amazon_data['product_name']+' '+amazon_data['category']+' '+amazon_data['about_product']+' '+amazon_data['img_link']+' '+amazon_data['product_link']+' '+amazon_data['review_title']+' '+amazon_data['review_content']

In [ ]:
print(combined_features)

0       Wayona Nylon Braided USB to Lightning Fast Cha...
1       Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
2       Sounce Fast Phone Charging Cable & Data Sync U...
3       boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...
4       Portronics Konnect L 1.2M Fast Charging 3A 8 P...
                              ...                        
1460    Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...
1461    Prestige Delight PRWO Electric Rice Cooker (1 ...
1462    Bajaj Majesty RX10 2000 Watts Heat Convector R...
1463    Havells Ventil Air DSP 230mm Exhaust Fan (Pist...
1464    Borosil Jumbo 1000-Watt Grill Sandwich Maker (...
Length: 1462, dtype: object


In [ ]:
#converting text data to feature vectors

vectorizer = TfidfVectorizer()

In [ ]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors)

  (0, 18408)	0.03496229029388053
  (0, 9717)	0.056901923510898955
  (0, 8300)	0.04794171586359642
  (0, 17859)	0.04075430760701405
  (0, 4939)	0.06286938083246783
  (0, 12067)	0.02137178487353487
  (0, 10300)	0.0380759006069192
  (0, 20410)	0.03564630720550761
  (0, 4562)	0.023536445816634978
  (0, 13122)	0.037666279165049055
  (0, 15430)	0.023781692063806096
  (0, 12073)	0.048798116255466886
  (0, 22403)	0.024827718009943885
  (0, 9065)	0.03978485297567247
  (0, 22563)	0.02503400224014921
  (0, 22810)	0.049476023553574
  (0, 11942)	0.03496229029388053
  (0, 4009)	0.040505683595649496
  (0, 10668)	0.08669569463830067
  (0, 3784)	0.07533024494325112
  (0, 17608)	0.03921084927687743
  (0, 22856)	0.03483761770631129
  (0, 15888)	0.041200131700667705
  (0, 20983)	0.029038928400018923
  (0, 19169)	0.07054111354575454
  :	:
  (1461, 16995)	0.09130377556642583
  (1461, 19583)	0.009710499460347743
  (1461, 17292)	0.009710499460347743
  (1461, 17669)	0.009710499460347743
  (1461, 9791)	0.009710

In [ ]:
similarity = cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[1.         0.30436002 0.39138057 ... 0.10614627 0.09005262 0.06182727]
 [0.30436002 1.         0.27192787 ... 0.10340259 0.07802083 0.08618333]
 [0.39138057 0.27192787 1.         ... 0.12199997 0.09571374 0.06512801]
 ...
 [0.10614627 0.10340259 0.12199997 ... 1.         0.14136632 0.10342093]
 [0.09005262 0.07802083 0.09571374 ... 0.14136632 1.         0.05887601]
 [0.06182727 0.08618333 0.06512801 ... 0.10342093 0.05887601 1.        ]]


In [ ]:
print(similarity.shape)

(1462, 1462)


chnages

In [ ]:
input_keywords = input("Enter keywords for your product: ")

Enter keywords for your product: Amazon Basics 16-Gauge Speaker Wire - 50 Feet


In [ ]:
input_vector = vectorizer.transform([input_keywords])

In [ ]:
input_similarity = cosine_similarity(input_vector, feature_vectors)[0]

In [ ]:
similar_product_indices = np.argsort(input_similarity)[::-1]

In [ ]:
# print('Products suggested for you:\n')
# i = 1
# for index in similar_product_indices:
#     if i < 10:
#         title = amazon_data.loc[index, 'product_name']
#         img_link = amazon_data.loc[index, 'img_link']
#         product_link = amazon_data.loc[index, 'product_link']
#         print(i, '.', title)
#         print('   Image Link:', img_link)
#         print('   Product Link:', product_link)
#         print()
#         i += 1

Product recommendation system

In [ ]:
# input_keywords = input("Enter keywords for your product: ")

# input_vector = vectorizer.transform([input_keywords])

# input_similarity = cosine_similarity(input_vector, feature_vectors)[0]

# similar_product_indices = np.argsort(input_similarity)[::-1]

# print('Products suggested for you:\n')
# i = 1
# for index in similar_product_indices:
#     if i < 10:
#         img_link = amazon_data.loc[index, 'img_link']
#         product_link = amazon_data.loc[index, 'product_link']

#         display(Image(url=img_link))
#         print(i, '.', title)
#         print('   Image Link:', img_link)
#         print('   Product Link:', product_link)
#         print()
#         i += 1





For exact product name use below code:

product_name = input("Enter your product name: ");

list_of_all_product_names = amazon_data['product_name'].tolist()
print(list_of_all_product_names)

find_close_match = difflib.get_close_matches(product_name, list_of_all_product_names)
print(find_close_match)

close_match = find_close_match[0]
print(close_match)

index_of_the_product = amazon_data[amazon_data.product_name == close_match]['index'].values[0]
print(index_of_the_product)

similarity_score = list(enumerate(similarity[index_of_the_product]))
print(similarity_score)


sorted_similar_products = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_products)


print('Products suggested for you : \n')

i = 1
amazon_data = amazon_data.reset_index(drop=True)
for product in sorted_similar_products:
  index = product[0]
  title_from_index = amazon_data[amazon_data.index==index]['product_name'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

In [ ]:
product_name = input("Enter your product name: ");

list_of_all_product_names = amazon_data['product_name'].tolist()
print(list_of_all_product_names)

find_close_match = difflib.get_close_matches(product_name, list_of_all_product_names)
print(find_close_match)

close_match = find_close_match[0]
print(close_match)

index_of_the_product = amazon_data[amazon_data.product_name == close_match]['index'].values[0]
print(index_of_the_product)

similarity_score = list(enumerate(similarity[index_of_the_product]))
print(similarity_score)


sorted_similar_products = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_products)


print('Products suggested for you : \n')

i = 1
amazon_data = amazon_data.reset_index(drop=True)
for product in sorted_similar_products:
  index = product[0]
  title_from_index = amazon_data[amazon_data.index==index]['product_name'].values[0]
  img_link = amazon_data.loc[index, 'img_link']
  if (i<10):
    print(i, '.',title_from_index)
    display(Image(url=img_link))
    i+=1

Enter your product name: Amazon Basics 16-Gauge Speaker Wire - 50 Feet
['Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)', 'Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)', 'Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices', 'boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)', 'Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)', 'pTron Solero TB301 3A Type-C Data and Fast Charging Cable, Made in India, 480Mbps Data Sync, Strong and Dur

2 . Zebronics ZEB-COUNTY 3W Wireless Bluetooth Portable Speaker With Supporting Carry Handle, USB, SD Card, AUX, FM & Call Function. (Green)


3 . Boya ByM1 Auxiliary Omnidirectional Lavalier Condenser Microphone with 20ft Audio Cable (Black)


4 . Amazonbasics Micro Usb Fast Charging Cable For Android Smartphone,Personal Computer,Printer With Gold Plated Connectors (6 Feet, Black)


5 . Amazonbasics Micro Usb Fast Charging Cable For Android Smartphone,Personal Computer,Printer With Gold Plated Connectors (6 Feet, Black)


6 . boAt Bassheads 152 in Ear Wired Earphones with Mic(Active Black)


7 . AmazonBasics Micro USB Fast Charging Cable for Android Phones with Gold Plated Connectors (3 Feet, Black)


8 . boAt Rockerz 400 Bluetooth On Ear Headphones With Mic With Upto 8 Hours Playback & Soft Padded Ear Cushions(Grey/Green)


9 . boAt Rockerz 400 Bluetooth On Ear Headphones With Mic With Upto 8 Hours Playback & Soft Padded Ear Cushions(Grey/Green)
